version: '2'
services:
  db:
    image: postgres:9.5.3
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bdss
      POSTGRES_USER: bdss
      POSTGRES_PASSWORD: topsecret
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  app:
    build: .
    command: ./scripts/serve --public
    environment:
      DATABASE_URL: postgresql+psycopg2://bdss:topsecret@db/bdss
      SESSION_KEY: f6280677c10b606b5a9be96a06893b41d5e2e803075b6c08462f738b5883d2ef
    links:
      - db
    ports:
      - 5000:5000
    volumes:
      - .:/app
